# frozen_string_literal: true

# The public-API surface lock. Everything under Charming::Internal is unversioned;
# every other Charming module constant is listed in PUBLIC_CONSTANTS. Adding or
# removing one fails this spec — update the list in the same PR so API drift is
# reviewable. `rake api:public` prints the current list. See API_POLICY.md.
RSpec.describe "API policy" do
  # All module constants under Charming except the Internal subtree (sorted).
  # standard:disable Lint/ConstantDefinitionInBlock
  PUBLIC_CONSTANTS = [
    "Application",
    "ApplicationState",
    "Audio",
    "Audio::Player",
    "Audio::Player::Unavailable",
    "Audio::System",
    "CLI",
    "CLI::ConsoleContext",
    "Component",
    "Components",
    "Components::ActivityIndicator",
    "Components::Audio",
    "Components::Autocomplete",
    "Components::Badge",
    "Components::Breadcrumbs",
    "Components::Chart",
    "Components::CommandPalette",
    "Components::CommandPalette::Command",
    "Components::CommandPaletteModal",
    "Components::EmptyState",
    "Components::ErrorScreen",
    "Components::Filepicker",
    "Components::Form",
    "Components::Form::Builder",
    "Components::Form::Confirm",
    "Components::Form::Field",
    "Components::Form::Input",
    "Components::Form::Multiselect",
    "Components::Form::Note",
    "Components::Form::Select",
    "Components::Form::Textarea",
    "Components::FuzzyMatcher",
    "Components::HelpOverlay",
    "Components::Image",
    "Components::KeyboardHandler",
    "Components::List",
    "Components::Markdown",
    "Components::Modal",
    "Components::MultiSelectList",
    "Components::Paginator",
    "Components::Progressbar",
    "Components::Result",
    "Components::Sparkline",
    "Components::Spinner",
    "Components::StatusBar",
    "Components::Stopwatch",
    "Components::TabBar",
    "Components::Table",
    "Components::TextArea",
    "Components::TextInput",
    "Components::TimeDisplay",
    "Components::Timer",
    "Components::Toast",
    "Components::Tree",
    "Components::Viewport",
    "Components::Viewport::ContentLines",
    "Components::Viewport::LineWindow",
    "Components::Viewport::Position",
    "Controller",
    "Controller::ActionHooks",
    "Controller::ActionHooks::ClassMethods",
    "Controller::ActionHooks::InstanceMethods",
    "Controller::ClassMethods",
    "Controller::ComponentDispatch",
    "Controller::Dispatching",
    "Controller::Focus",
    "Controller::FocusManagement",
    "Controller::KeyDispatch",
    "Controller::Rendering",
    "Controller::SessionState",
    "Controller::TaskBinding",
    "Controller::Terminal",
    "Controller::TimerBinding",
    "Controller::Timers",
    "CrossThreadAccess",
    "Database",
    "Database::Commands",
    "DoubleRenderError",
    "Error",
    "Escape",
    "Escape::Sequence",
    "Events",
    "Events::FocusEvent",
    "Events::KeyEvent",
    "Events::MouseEvent",
    "Events::PasteEvent",
    "Events::ResizeEvent",
    "Events::TaskEvent",
    "Events::TaskProgressEvent",
    "Events::TimerEvent",
    "Generators",
    "Generators::AppFileGenerator",
    "Generators::AppGenerator",
    "Generators::Base",
    "Generators::ComponentGenerator",
    "Generators::ControllerGenerator",
    "Generators::DatabaseInstaller",
    "Generators::Error",
    "Generators::LayoutGenerator",
    "Generators::MigrationGenerator",
    "Generators::MigrationGenerator::Field",
    "Generators::MigrationTimestamp",
    "Generators::ModelGenerator",
    "Generators::ModelGenerator::Field",
    "Generators::Name",
    "Generators::ScreenGenerator",
    "Generators::ViewGenerator",
    "Image",
    "Image::Protocol",
    "Image::Protocol::Kitty",
    "Image::Source",
    "Image::Terminal",
    "Image::Transmit",
    "Layout",
    "Layout::Builder",
    "Layout::Overlay",
    "Layout::Pane",
    "Layout::PaneBehavior",
    "Layout::PaneGeometry",
    "Layout::PaneStyle",
    "Layout::Rect",
    "Layout::ScreenLayout",
    "Layout::Split",
    "Markdown",
    "Markdown::RenderContext",
    "Markdown::Renderer",
    "Markdown::StyleConfig",
    "Markdown::StyleConfig::Style",
    "Markdown::SyntaxHighlighter",
    "Markdown::TableRenderer",
    "Markdown::URLResolver",
    "Projectile",
    "Projectile::Point",
    "Projectile::Vector",
    "RenderArtifacts",
    "Response",
    "Router",
    "Router::Route",
    "Runtime",
    "Screen",
    "Shell",
    "Shell::Palette",
    "Shell::Palette::ClassMethods",
    "Shell::Sidebar",
    "Spring",
    "Tasks",
    "Tasks::Cancelled",
    "Tasks::Context",
    "Tasks::InlineExecutor",
    "Tasks::Progress",
    "Tasks::Task",
    "Tasks::ThreadedExecutor",
    "TemplateView",
    "Templates",
    "Templates::ErbHandler",
    "Templates::MissingTemplateError",
    "Templates::ResolvedTemplate",
    "TestHelper",
    "UI",
    "UI::ANSICodes",
    "UI::ANSISlicer",
    "UI::AdaptiveColor",
    "UI::Background",
    "UI::Border",
    "UI::BorderPainter",
    "UI::BrailleCanvas",
    "UI::Canvas",
    "UI::ColorSupport",
    "UI::Gradient",
    "UI::Style",
    "UI::TextWrapper",
    "UI::Theme",
    "UI::Truncate",
    "UI::Width",
    "UnhandledComponentEvent",
    "UnknownSlot",
    "View",
    "Welcome",
    "Welcome::Controller",
    "Welcome::ShowView"
  ].freeze
  # standard:enable Lint/ConstantDefinitionInBlock

  def public_constants
    Zeitwerk::Loader.eager_load_all
    collected = []
    walk = lambda do |mod, prefix, &block|
      mod.constants(false).sort.each do |name|
        const = mod.const_get(name)
        next unless const.is_a?(Module)

        path = prefix + [name]
        block.call(path)
        walk.call(const, path, &block) if path.length < 4
      end
    end
    walk.call(Charming, []) do |path|
      collected << path.join("::") if path.first != :Internal
    end
    collected.sort
  end

  it "matches the checked-in public constant list" do
    expect(public_constants).to eq(PUBLIC_CONSTANTS)
  end
end
